// Generated by Scripts/gen_tokens.py from design/handoff/lumina-app/parity/tokens.json. Do not edit.
import SwiftUI

public enum LuminaColor {
    public static let bgApp = Color(.sRGB, red: 30 / 255, green: 29 / 255, blue: 27 / 255, opacity: 1)
    public static let bgPanel = Color(.sRGB, red: 38 / 255, green: 37 / 255, blue: 35 / 255, opacity: 1)
    public static let bgPanelHover = Color(.sRGB, red: 44 / 255, green: 43 / 255, blue: 41 / 255, opacity: 1)
    public static let bgCanvas = Color(.sRGB, red: 22 / 255, green: 21 / 255, blue: 20 / 255, opacity: 1)
    public static let bgSelected = Color(.sRGB, red: 91 / 255, green: 88 / 255, blue: 84 / 255, opacity: 1)
    public static let textPrimary = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 1)
    public static let textSecondary = Color(.sRGB, red: 184 / 255, green: 179 / 255, blue: 171 / 255, opacity: 1)
    public static let textTertiary = Color(.sRGB, red: 150 / 255, green: 145 / 255, blue: 138 / 255, opacity: 1)
    public static let textDisabled = Color(.sRGB, red: 110 / 255, green: 106 / 255, blue: 100 / 255, opacity: 1)
    public static let textOnPrimary = Color(.sRGB, red: 30 / 255, green: 29 / 255, blue: 27 / 255, opacity: 1)
    public static let accentGold = Color(.sRGB, red: 255 / 255, green: 210 / 255, blue: 122 / 255, opacity: 1)
    public static let accentGoldTint = Color(.sRGB, red: 255 / 255, green: 210 / 255, blue: 122 / 255, opacity: 0.08)
    public static let accentGoldLine = Color(.sRGB, red: 255 / 255, green: 210 / 255, blue: 122 / 255, opacity: 0.25)
    public static let accentGoldGlow = Color(.sRGB, red: 255 / 255, green: 210 / 255, blue: 122 / 255, opacity: 0.35)
    public static let accentGoldDash = Color(.sRGB, red: 255 / 255, green: 210 / 255, blue: 122 / 255, opacity: 0.7)
    public static let primaryFill = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 1)
    public static let primaryHover = Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1)
    public static let errorText = Color(.sRGB, red: 240 / 255, green: 163 / 255, blue: 158 / 255, opacity: 1)
    public static let errorDot = Color(.sRGB, red: 229 / 255, green: 83 / 255, blue: 75 / 255, opacity: 1)
    public static let errorBg = Color(.sRGB, red: 229 / 255, green: 83 / 255, blue: 75 / 255, opacity: 0.08)
    public static let successDot = Color(.sRGB, red: 127 / 255, green: 196 / 255, blue: 107 / 255, opacity: 1)
    public static let overlayScrim = Color(.sRGB, red: 22 / 255, green: 21 / 255, blue: 20 / 255, opacity: 0.86)
    public static let overlayChip = Color(.sRGB, red: 22 / 255, green: 21 / 255, blue: 20 / 255, opacity: 0.82)
    public static let shadowTabThumb = Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.4)
    public static let fill04 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.04)
    public static let fill06 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.06)
    public static let fill07 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.07)
    public static let fill08 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.08)
    public static let fill09 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.09)
    public static let fill10 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.1)
    public static let fill12 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.12)
    public static let fill13 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.13)
    public static let fill16 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.16)
    public static let fill20 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.2)
    public static let fill22 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.22)
    public static let fill24 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.24)
    public static let fill28 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.28)
    public static let fill35 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.35)
    public static let fill50 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.5)
    public static let fill55 = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.55)
    public static let hairline = Color(.sRGB, red: 239 / 255, green: 236 / 255, blue: 230 / 255, opacity: 0.08)
    public static let swatch: [String: Color] = ["red": Color(.sRGB, red: 229 / 255, green: 83 / 255, blue: 75 / 255, opacity: 1), "orange": Color(.sRGB, red: 232 / 255, green: 145 / 255, blue: 58 / 255, opacity: 1), "yellow": Color(.sRGB, red: 227 / 255, green: 200 / 255, blue: 75 / 255, opacity: 1), "green": Color(.sRGB, red: 93 / 255, green: 184 / 255, blue: 96 / 255, opacity: 1), "aqua": Color(.sRGB, red: 76 / 255, green: 195 / 255, blue: 192 / 255, opacity: 1), "blue": Color(.sRGB, red: 76 / 255, green: 130 / 255, blue: 224 / 255, opacity: 1), "purple": Color(.sRGB, red: 142 / 255, green: 98 / 255, blue: 217 / 255, opacity: 1), "magenta": Color(.sRGB, red: 212 / 255, green: 90 / 255, blue: 181 / 255, opacity: 1)]
}

/// Font sizes in points, before × luminaScale. Use them through `LuminaFont`.
public enum LuminaFontSize {
    public static let hint: CGFloat = 11
    public static let small: CGFloat = 12
    public static let caption: CGFloat = 12.5
    public static let body: CGFloat = 13
    public static let bodyLarge: CGFloat = 13.5
    public static let button: CGFloat = 14
    public static let title3: CGFloat = 15
    public static let title2: CGFloat = 16
    public static let overlayTitle: CGFloat = 18
    public static let wordmark: CGFloat = 21
    public static let title1: CGFloat = 24
    public static let display: CGFloat = 28
    public static let monoHint: CGFloat = 11.5
    public static let minimum: CGFloat = 11
    public static let displayFamilies = ["Iowan Old Style", "Palatino", "Georgia"]
    public static let monoFamilies = ["SF Mono", "Menlo"]
    public static let lineHeightBody: CGFloat = 1.5
}

public enum LuminaRadius {
    public static let photo: CGFloat = 3
    public static let tile: CGFloat = 3
    public static let thumbInner: CGFloat = 2
    public static let tabThumb: CGFloat = 5
    public static let chip: CGFloat = 6
    public static let tabTrack: CGFloat = 7
    public static let pill: CGFloat = 7
    public static let buttonSecondary: CGFloat = 8
    public static let buttonPrimary: CGFloat = 9
    public static let row: CGFloat = 9
    public static let segmented: CGFloat = 10
    public static let saveButton: CGFloat = 10
    public static let toggleRow: CGFloat = 10
    public static let card: CGFloat = 12
    public static let dropOverlay: CGFloat = 14
}

public enum LuminaHeight {
    public static let tab: CGFloat = 24
    public static let chip: CGFloat = 24
    public static let pill: CGFloat = 28
    public static let buttonSecondary: CGFloat = 32
    public static let footerButton: CGFloat = 34
    public static let segment: CGFloat = 34
    public static let buttonPrimary: CGFloat = 36
    public static let keepOut: CGFloat = 36
    public static let saveButton: CGFloat = 40
    public static let sliderRowMin: CGFloat = 28
    public static let minHit: CGFloat = 28
}

public enum LuminaSpacing {
    public static let steps: [CGFloat] = [4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 28, 44, 56]
    public static let tileGap: CGFloat = 6
    public static let sceneGap: CGFloat = 20
    public static let cullPadding: [CGFloat] = [16, 20, 24]
    public static let photoPaddingMax: CGFloat = 12
    public static let lowResBlur: CGFloat = 6
}

/// Durations and curves. Go through `LuminaMotion.x(reduce)` so reduced motion turns them off.
public enum LuminaMotion {
    public static let stepFadeSeconds: Double = 0.16
    public static func stepFade(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.easeOut(duration: 0.16) }
    public static let panelFadeSeconds: Double = 0.12
    public static func panelFade(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.easeOut(duration: 0.12) }
    public static let tabThumbSeconds: Double = 0.16
    public static func tabThumb(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.easeOut(duration: 0.16) }
    public static let tileFadeSeconds: Double = 0.12
    public static func tileFade(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.easeOut(duration: 0.12) }
    public static let outDimSeconds: Double = 0.12
    public static func outDim(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.easeOut(duration: 0.12) }
    public static let keepPopSeconds: Double = 0.2
    public static let savedCardSeconds: Double = 0.18
    public static func savedCard(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.easeOut(duration: 0.18) }
    public static let savedCardRise: CGFloat = 4
    public static let sliderFillSeconds: Double = 0.16
    public static func sliderFill(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.timingCurve(0.2, 0.8, 0.2, 1, duration: 0.16) }
    public static let thumbScaleSeconds: Double = 0.22
    public static func thumbScale(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.timingCurve(0.34, 1.56, 0.64, 1, duration: 0.22) }
    public static let thumbScaleHover: CGFloat = 1.15
    public static let thumbScaleDrag: CGFloat = 1.25
    public static let thumbScaleSnapped: CGFloat = 1.5
    public static let sharpFadeInSeconds: Double = 0.15
    public static func sharpFadeIn(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.easeOut(duration: 0.15) }
    public static let cropBoxSeconds: Double = 0.22
    public static func cropBox(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.timingCurve(0.2, 0.8, 0.2, 1, duration: 0.22) }
    public static let copyBarSeconds: Double = 0.08
    public static func copyBar(_ reduce: Bool = false) -> Animation? { reduce ? nil : Animation.linear(duration: 0.08) }
}

public enum LuminaSlider {
    public static let track: CGFloat = 2.5
    public static let trackHover: CGFloat = 4
    public static let trackHit: CGFloat = 20
    public static let zeroTick: CGFloat = 6
    public static let zeroTickSnapped: CGFloat = 12
    public static let snapWithin: CGFloat = 0.012
    public static let fine: CGFloat = 0.25
    public static let finer: CGFloat = 0.1
}
