#!/usr/bin/env python3
"""Kill-anywhere loop (release task Q3, `bash Scripts/probe.sh life`, docs/release/stress/Q3-lifecycle.md).

Each launch is one probe process in app mode (the real page, plumbing.js and the app's bridge), with
one support folder (sessions) and one shoot folder kept across launches. A launch opens the shoot
(the first time, and after a kill that came before the shoot was known, through the folder panel;
otherwise through the Open screen's recent, i.e. the bookmark), dumps the decisions it reopened
with, then culls with seeded keys (keep, un-keep, flag, flag a stack, move, split, merge, undo),
dumping the decisions after every key. At a seeded moment this script SIGKILLs that process (the
probe's own pid, or, sandboxed, the sandboxed child of this run's own launcher: never anything
found by name). The next launch's reopened decisions must equal one of the states the killed
launch went through, and that state may be older than the kill by at most --allow-ms (500: the
session debounce); `lost` is the time from the first change missing to the kill.

Decisions = marks ('keep'), flags, stars and cuts (splits / merges), by file name. Not the cursor,
seen rows or tile size. Evidence: <out>/results.jsonl (one line per kill: seed, kill time, phase,
verdict, lost ms), <out>/summary.json, and each launch's scenario, dumps and report under <out>.
"""
import argparse, json, os, random, shutil, signal, statistics, subprocess, sys, time

DECISIONS = (
    "const l=__probe.logic(), s=l.state, nm=id=>{const p=l.data&&l.data.byId&&l.data.byId[id]; return p?p.file:String(id)};"
    "const pick=(m,keep)=>{const o={}; for (const [id,v] of Object.entries(m||{})) if (keep(v)) o[nm(id)]=v; return o;};"
    "return {t: performance.timeOrigin+performance.now(), view: s.view, loaded: !!(l.real&&!s.realLoad),"
    " shoot: (window.__lumina&&__lumina.shootId)?__lumina.shootId():null,"
    " d: {marks: pick(s.marks, v=>v==='keep'), flags: pick(s.flags, v=>!!v), stars: pick(s.stars, v=>!!v),"
    " cuts: pick(s.cuts, v=>v!==undefined&&v!==null)}};"
)

def build_scenario(template, i, seed, shoot, support, first_open, actions, gap):
    rng = random.Random(seed)
    spec = {k: v for k, v in template.items() if k not in ("steps", "life", "checklist")}
    spec["supportDir"] = support
    spec["stopOnFailure"] = True
    spec["checklist"] = f"Q3 kill-anywhere launch {i}, seed {seed} (generated by Tests/probe/life_kill.py)"
    steps = []
    if first_open:
        steps.append({"do": "openFolder", "path": shoot, "timeoutMs": 60000})
    else:
        steps += [{"do": "waitFor", "js": "return __probe.logic().recents().length > 0", "timeoutMs": 20000, "what": "recents"},
                  {"do": "key", "k": "Enter", "settleMs": 0},
                  {"do": "waitFor", "js": "const l=__probe.logic(); return !!(l.real && !l.state.realLoad && l.state.realInfo && __lumina.shootId())",
                   "timeoutMs": 60000, "what": "reopened"}]
    steps.append({"do": "dump", "name": "opened", "js": DECISIONS})
    keys, weights = zip(*[(tuple(k), w) for k, w in template["life"]["keys"]])
    plan = []
    for j in range(1, actions + 1):
        k, shift = rng.choices(keys, weights)[0]
        g = rng.uniform(*gap) if rng.random() > 0.25 else rng.uniform(0, 30)
        plan.append((k, shift, round(g)))
        steps += [{"do": "key", "k": k, "shift": shift, "settleMs": 0},
                  {"do": "dump", "name": f"a{j:03d}", "js": DECISIONS},
                  {"do": "wait", "ms": round(g)}]
    steps.append({"do": "wait", "ms": 3000, "why": "not killed: let the session land before the process ends"})
    spec["steps"] = steps
    return spec, plan

def read_trail(d):
    trail = []
    if not os.path.isdir(d): return trail
    for f in sorted(os.listdir(d)):
        if f.endswith(".json") and (f == "opened.json" or (f.startswith("a") and f[1:4].isdigit())):
            try: trail.append((f[:-5], json.load(open(os.path.join(d, f)))))
            except Exception: pass                      # a dump torn by the kill: never written atomically? (it is: atomic write)
    order = {"opened": -1}
    return sorted(trail, key=lambda x: order.get(x[0], int(x[0][1:]) if x[0][1:].isdigit() else 0))

def child_of(ppid, timeout=10):
    end = time.time() + timeout
    while time.time() < end:
        r = subprocess.run(["/usr/bin/pgrep", "-P", str(ppid)], capture_output=True, text=True)
        pids = [int(x) for x in r.stdout.split()]
        if pids: return pids[0]
        time.sleep(0.02)
    return None

def judge(prev, R, allow_ms):
    """prev: the killed launch ({trail, kill_ms}). R: decisions reopened by the next launch."""
    trail, K = prev["trail"], prev["kill_ms"]
    # States in order: what it reopened with ("opened"), then after each key. Each dump is taken
    # right after its key is sent (no settle), so a dump's time is when that state began (± a few ms).
    states = [(name, x["t"], x["d"]) for name, x in trail]
    # The latest state equal to R. Lost = kill time − when the first change R lacks appeared.
    for idx in range(len(states) - 1, -1, -1):
        if states[idx][2] == R:
            first_missing = next((s for s in states[idx + 1:] if s[2] != R), None)
            if first_missing is None:
                return {"verdict": "pass", "match": states[idx][0], "lost": 0}
            lost = max(0, K - first_missing[1])
            return {"verdict": "pass" if lost <= allow_ms else "FAIL", "match": states[idx][0], "lost": round(lost),
                    "why": None if lost <= allow_ms else f"decisions of the last {round(lost)} ms lost (allowed {int(allow_ms)}); kept state {states[idx][0]}, first lost {first_missing[0]}"}
    return {"verdict": "FAIL", "lost": None, "why": "reopened decisions equal no state the killed launch went through (a key in flight at the kill, or a damaged session)",
            "reopened": R, "last": states[-1][2], "last_name": states[-1][0], "ms_since_last_dump": round(K - states[-1][1])}

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--probe", required=True)
    ap.add_argument("--sandbox", help="the sandboxed lumina-probe (probe.sh sandbox builds it)")
    ap.add_argument("--template", default="Tests/probe/scenarios/life-kill-cull.json")
    ap.add_argument("--out", required=True)
    ap.add_argument("--kills", type=int, default=200)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--allow-ms", type=float, default=500)
    a = ap.parse_args()
    fixtures = os.environ.get("LUMINA_FIXTURE_ROOT", "")
    if not fixtures or not os.path.isdir(os.path.join(fixtures, "src")):
        print("SKIP  life-kill (LUMINA_FIXTURE_ROOT/src is not set)"); return 0
    template = json.load(open(a.template))
    life = template["life"]
    out = os.path.abspath(a.out); os.makedirs(out, exist_ok=True)
    shoot = os.path.join(out, "shoot", "src")
    if not os.path.isdir(shoot):
        os.makedirs(os.path.dirname(shoot), exist_ok=True)
        subprocess.run(["/bin/cp", "-Rc", os.path.join(fixtures, "src"), shoot], check=True)
    stamp = os.path.basename(out.rstrip("/")) + "-" + str(int(time.time()))
    if a.sandbox:
        # The app keeps sessions in its container; the sandboxed probe's container is its own. Only
        # this run's subfolder, named per run; this script never opens the container itself.
        support = os.path.expanduser(f"~/Library/Containers/com.lumina.probe.sandboxed/Data/Library/Application Support/LuminaProbe/life/{stamp}")
    else:
        support = os.path.join(out, "support")
    # The generated scenarios. Sandboxed, the probe reads scenarios through its read-only grant on
    # the checkout (the app bundle's stand-in), so they go under the checkout's ignored .build too.
    gen = os.path.join(out, "gen"); os.makedirs(gen, exist_ok=True)
    if a.sandbox:
        gen = os.path.join(os.getcwd(), "Tools/LuminaProbe/.build/life-gen", stamp); os.makedirs(gen, exist_ok=True)
    results = open(os.path.join(out, "results.jsonl"), "w")
    env = dict(os.environ)
    master = random.Random(a.seed)
    prev, opened_before, rows, launches = None, False, [], []
    t_run = time.time()
    for i in range(a.kills + 1):                 # the last launch only reopens and checks
        final = i == a.kills
        seed = a.seed * 100000 + i
        name = f"life-kill-{i:04d}"
        spec, plan = build_scenario(template, i, seed, shoot, support, not opened_before, 0 if final else life["actions"], life["gapMs"])
        sp = os.path.join(gen, name + ".json")
        json.dump(spec, open(sp, "w"), indent=1)
        if a.sandbox: shutil.copy(sp, os.path.join(out, "gen", name + ".json"))
        launch_out = out
        if a.sandbox:
            cmd = [a.probe, "sandbox-launch", a.sandbox, "--info", os.path.join(out, name, "sandbox-launch.json"), "--", "run", sp, "--out", launch_out, "--deadline", "300"]
        else:
            cmd = [a.probe, "run", sp, "--out", launch_out, "--deadline", "300"]
        kill_after = None if final else master.uniform(*life["killAfterS"])
        t0 = time.time()
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, env=env)
        target = child_of(p.pid) if a.sandbox else p.pid
        killed, kill_ms = False, None
        if kill_after is not None and target:
            while time.time() - t0 < kill_after and p.poll() is None: time.sleep(0.005)
            if p.poll() is None:
                kill_ms = time.time() * 1000
                try: os.kill(target, signal.SIGKILL); killed = True
                except ProcessLookupError: pass
        try: stdout = p.communicate(timeout=360)[0].decode(errors="replace")
        except subprocess.TimeoutExpired:
            p.kill(); stdout = "timed out"
            if target and target != p.pid:
                try: os.kill(target, signal.SIGKILL)
                except ProcessLookupError: pass
        trail = read_trail(os.path.join(out, name))
        opened = next((x for n, x in trail if n == "opened"), None)
        row = {"i": i, "seed": seed, "first_open": not opened_before, "kill_after_s": round(kill_after, 3) if kill_after else None,
               "killed": killed, "exit": p.returncode, "dumps": len(trail),
               "phase": ("final reopen" if final else "launch / open (before the shoot showed)" if not opened else f"culling, after {len(trail) - 1} keys")}
        if not killed and not final:
            row["note"] = "process ended before the kill"
            if p.returncode not in (0, None): row["note"] += f": exit {p.returncode}: " + stdout.strip()[-400:]
        # Judge the last launch that showed the shoot by what this one reopened with. A launch killed
        # before it showed the shoot cannot have changed the session: the judgement waits for the next.
        if opened is not None:
            if prev is not None:
                v = judge(prev, opened["d"], a.allow_ms)
                v["of"] = prev["i"]
                if prev.get("stalled"):
                    # The kill came late by seconds: the Mac slept or stalled mid-launch (wall clock jumped).
                    v["measured"] = v["verdict"]; v["verdict"] = "excluded"
                    v["why"] = f"the kill landed {prev['stalled']} s late (the Mac slept or stalled): not counted · " + (v.get("why") or "")
                row["previous"] = v
                rows.append(v | {"seed": prev["seed"], "phase": prev["phase"], "kill_after_s": prev["kill_after_s"],
                                 "launches_between": i - prev["i"] - 1})
            opened_before = True
            late = round(kill_ms / 1000 - t0 - kill_after, 1) if kill_ms and kill_after else 0
            if late > 1: row["stalled_s"] = late
            prev = {"i": i, "seed": seed, "trail": trail, "kill_ms": kill_ms or time.time() * 1000,
                    "phase": row["phase"], "kill_after_s": row["kill_after_s"], "stalled": late if late > 1 else 0}
        elif prev is not None:
            row["judged"] = f"killed before it reopened: launch {prev['i']} is judged by the next one"
        launches.append(row)
        results.write(json.dumps(row) + "\n"); results.flush()
        pv = row.get("previous")
        print(f"  {name} seed {seed} {row['phase']:<44} " + ("killed" if killed else "not killed") +
              (f" @ {row['kill_after_s']} s" if row['kill_after_s'] else "") +
              (f" · kill {pv['of']}: {pv['verdict']} lost {pv['lost']} ms" if pv else ""), flush=True)
        if final and not opened:
            rows.append({"verdict": "FAIL", "why": "the final reopen did not show the shoot: " + stdout.strip()[-400:], "of": prev["i"] if prev else None})
    judged = [r for r in rows if "of" in r]
    excluded = [r for r in judged if r["verdict"] == "excluded"]
    judged = [r for r in judged if r["verdict"] != "excluded"]
    lost = [r["lost"] for r in judged if isinstance(r.get("lost"), (int, float))]
    fails = [r for r in judged if r["verdict"] != "pass"]
    lost_nonzero = [x for x in lost if x > 0]
    summary = {"mode": "sandboxed" if a.sandbox else "unsandboxed", "kills": a.kills, "seed": a.seed, "allow_ms": a.allow_ms,
               "judged": len(judged), "pass": len(judged) - len(fails), "fail": len(fails),
               "fail_lost_over_allow": sum(1 for r in fails if r.get("lost") is not None),
               "fail_no_matching_state": sum(1 for r in fails if r.get("lost") is None),
               "lost_ms": {"n_nonzero": len(lost_nonzero), "max": max(lost) if lost else 0,
                           "median_nonzero": statistics.median(lost_nonzero) if lost_nonzero else 0,
                           "over_500": sum(x > 500 for x in lost), "over_2000": sum(x > 2000 for x in lost), "over_2500": sum(x > 2500 for x in lost)},
               "excluded": excluded, "lost_all_ms": sorted(lost), "phases": {}, "seconds": round(time.time() - t_run), "support": support, "fails": fails[:40]}
    for r in launches:
        if r["killed"]:
            k = r["phase"].split(",")[0]; summary["phases"][k] = summary["phases"].get(k, 0) + 1
    summary["killed"] = sum(r["killed"] for r in launches)
    summary["not_killed"] = [r for r in launches if not r["killed"] and r["phase"] != "final reopen"]
    json.dump(summary, open(os.path.join(out, "summary.json"), "w"), indent=1)
    print(f"{'PASS' if not fails else 'FAIL'}  life-kill ({summary['mode']}): {summary['pass']}/{summary['judged']} kills within {int(a.allow_ms)} ms · "
          f"lost > 500 ms: {summary['lost_ms']['over_500']}, > 2 s: {summary['lost_ms']['over_2000']}, max {summary['lost_ms']['max']} ms · "
          f"no matching state: {summary['fail_no_matching_state']} → {out}/summary.json")
    return 1 if fails else 0

if __name__ == "__main__":
    sys.exit(main())
