#!/usr/bin/env python3
"""Generates LuminaKit/Sources/LuminaUI/Tokens/Tokens.generated.swift from the design's tokens.json
(design/handoff/lumina-app/parity/tokens.json). Token values are never typed by hand in Swift:
change the JSON, run this, review the diff.   python3 Scripts/gen_tokens.py [--check]"""
import json, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "design/handoff/lumina-app/parity/tokens.json"
OUT = ROOT / "LuminaKit/Sources/LuminaUI/Tokens/Tokens.generated.swift"

def ident(name):
    parts = re.split(r"[.\-_ ]", name)
    s = parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    return s if not s[0].isdigit() else "_" + s

def colour(v):
    if v.startswith("#"):
        r, g, b = (int(v[i:i + 2], 16) for i in (1, 3, 5)); a = 1.0
    else:
        r, g, b, a = (float(x) for x in re.match(r"rgba\(([^)]+)\)", v).group(1).split(","))
    return f"Color(.sRGB, red: {int(r)} / 255, green: {int(g)} / 255, blue: {int(b)} / 255, opacity: {a:g})"

def num(v): return f"{v:g}"

def anim(m):
    d = m["ms"] / 1000
    if "bezier" in m:
        a, b, c, e = m["bezier"]; return f"Animation.timingCurve({a:g}, {b:g}, {c:g}, {e:g}, duration: {d:g})"
    return f"Animation.{ {'easeOut': 'easeOut', 'linear': 'linear'}[m.get('easing', 'easeOut')] }(duration: {d:g})"

t = json.loads(SRC.read_text())
L = ["// Generated by Scripts/gen_tokens.py from design/handoff/lumina-app/parity/tokens.json. Do not edit.",
     "import SwiftUI", "", "public enum LuminaColor {"]
for k, v in t["color"].items():
    if k == "swatch":
        L.append("    public static let swatch: [String: Color] = [" + ", ".join(f'"{n}": {colour(c)}' for n, c in v.items()) + "]")
    else:
        L.append(f"    public static let {ident(k)} = {colour(v)}")
L += ["}", "", "/// Font sizes in points, before × luminaScale. Use them through `LuminaFont`.", "public enum LuminaFontSize {"]
L += [f"    public static let {ident(k)}: CGFloat = {num(v)}" for k, v in t["font"]["size"].items()]
L += [f"    public static let minimum: CGFloat = {num(t['font']['minimum'])}",
      "    public static let displayFamilies = [" + ", ".join(f'"{f}"' for f in t["font"]["display"]) + "]",
      "    public static let monoFamilies = [" + ", ".join(f'"{f}"' for f in t["font"]["mono"]) + "]",
      f"    public static let lineHeightBody: CGFloat = {num(t['font']['lineHeight']['body'])}",
      "}", "", "public enum LuminaRadius {"]
L += [f"    public static let {ident(k)}: CGFloat = {num(v)}" for k, v in t["radius"].items()]
L += ["}", "", "public enum LuminaHeight {"]
L += [f"    public static let {ident(k)}: CGFloat = {num(v)}" for k, v in t["height"].items() if not isinstance(v, dict)]
L += ["}", "", "public enum LuminaSpacing {",
      "    public static let steps: [CGFloat] = [" + ", ".join(num(v) for v in t["spacing"]) + "]"]
c = t["layout"]["cull"]
L += [f"    public static let tileGap: CGFloat = {num(c['tileGap'])}", f"    public static let sceneGap: CGFloat = {num(c['sceneGap'])}",
      "    public static let cullPadding: [CGFloat] = [" + ", ".join(num(v) for v in c["padding"]) + "]",
      f"    public static let photoPaddingMax: CGFloat = {num(t['layout']['edit']['photoPaddingMax'])}",
      f"    public static let lowResBlur: CGFloat = {num(t['layout']['edit']['lowResBlur'])}",
      "}", "", "/// Durations and curves. Go through `LuminaMotion.x(reduce)` so reduced motion turns them off.", "public enum LuminaMotion {"]
for k, m in t["motion"].items():
    if not isinstance(m, dict): continue
    L.append(f"    public static let {ident(k)}Seconds: Double = {m['ms'] / 1000:g}")
    if "keyframes" not in m:
        L.append(f"    public static func {ident(k)}(_ reduce: Bool = false) -> Animation? {{ reduce ? nil : {anim(m)} }}")
    for extra in ("rise", "hover", "drag", "snapped"):
        if extra in m: L.append(f"    public static let {ident(k)}{extra.capitalize()}: CGFloat = {num(m[extra])}")
L += ["}", "", "public enum LuminaSlider {"]
L += [f"    public static let {ident(k)}: CGFloat = {num(v)}" for k, v in t["slider"].items()]
L += ["}", ""]
text = "\n".join(L)
if "--check" in sys.argv:
    sys.exit(0 if OUT.exists() and OUT.read_text() == text else "Tokens.generated.swift is stale: run python3 Scripts/gen_tokens.py")
OUT.write_text(text); print("wrote", OUT.relative_to(ROOT))
