#!/usr/bin/env python3
"""Auto fixtures for the browser design (BRIDGE-v0.02 §1, prompts/PROMPT-auto-backend.md).

Writes data/auto-fixtures.js: `window.LuminaAutoFixtures = { "DSC06175.ARW": {ev, wb, tint, hl, sh, wh, bl}, … }`,
AutoDevelop's real output (`lumina-render auto`, the same code the app's `lumina.auto` runs) for every RAW behind
the sample shoot (the stems of SAMPLE_IMGS in lumina-v4-data.js, uploads/DSC*.jpg) and every ARW fixture. With it
loaded, the browser design shows the recorded Auto ("Auto · recorded") instead of its JPEG estimate.

Needs the Mac and the RAWs (`make auto-fixtures`). Values are never typed in by hand: a RAW that is missing or that
lumina-render can't develop fails the run (exit 1) and nothing is written, unless --allow-missing.

  python3 Tools/auto/auto_fixtures.py --render <lumina-render> [--sample DIR] [--fixtures DIR] [--out FILE] [--rules FILE]
  python3 Tools/auto/auto_fixtures.py --from-jsonl auto.jsonl [--out FILE]     # from a saved `lumina-render auto` run

The page looks a photo up by its file name and then by its stem (`F[p.file] || F[stem]`), and the Edit step names a
read photo by its stem: each entry is written under both.
"""
import argparse
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA_JS = os.path.join(ROOT, 'design/handoff/lumina-cull/lumina-v4-data.js')
DEFAULT_OUT = os.path.join(ROOT, 'design/handoff/lumina-cull/data/auto-fixtures.js')
KEYS = ['ev', 'wb', 'tint', 'hl', 'sh', 'wh', 'bl', 'con']
BATCH = 40


def sample_stems(data_js=DATA_JS):
    """The sample shoot's camera files, from SAMPLE_IMGS in lumina-v4-data.js ("DSC06175.jpg" → "DSC06175").
    Only uploads/DSC*.jpg have a RAW behind them; the other sample images (phone shots, stock) have none."""
    with open(data_js, encoding='utf-8') as f:
        text = f.read()
    m = re.search(r'const SAMPLE_IMGS\s*=\s*\[(.*?)\]', text, re.S)
    if not m:
        raise SystemExit('auto-fixtures: SAMPLE_IMGS not found in ' + data_js)
    return [os.path.splitext(n)[0] for n in re.findall(r'"([^"]+)"', m.group(1)) if re.match(r'DSC\w+\.jpe?g$', n, re.I)]


def find_raws(folder, stems=None):
    """ARWs in `folder` (not recursive), by stem when `stems` is given. Returns (paths, missing stems)."""
    if not folder or not os.path.isdir(folder):
        return [], list(stems or [])
    by_stem = {}
    for n in sorted(os.listdir(folder)):
        if n.lower().endswith('.arw'):
            by_stem.setdefault(os.path.splitext(n)[0].lower(), os.path.join(folder, n))
    if stems is None:
        return list(by_stem.values()), []
    found, missing = [], []
    for s in stems:
        p = by_stem.get(s.lower())
        (found.append(p) if p else missing.append(s))
    return found, missing


def run_render(render, paths, rules=None):
    """`lumina-render auto` over `paths`, in batches; one parsed JSON line per file."""
    out = []
    for i in range(0, len(paths), BATCH):
        cmd = [render, 'auto'] + paths[i:i + BATCH] + (['--rules', rules] if rules else [])
        r = subprocess.run(cmd, capture_output=True, text=True)
        lines = [json.loads(l) for l in r.stdout.splitlines() if l.strip().startswith('{')]
        if not lines:
            raise SystemExit('auto-fixtures: lumina-render auto gave nothing: ' + r.stderr.strip())
        out.extend(lines)
    return out


def entries(lines):
    """{file name: look}, the version, and the failures, from `lumina-render auto` lines."""
    table, versions, failed = {}, set(), []
    for l in lines:
        name = os.path.basename(str(l.get('image', '')))
        look = l.get('look') if l.get('ok') else None
        if not name or not isinstance(look, dict):
            failed.append((name or '?', l.get('error', 'no look')))
            continue
        clean = {k: look[k] for k in KEYS if isinstance(look.get(k), (int, float)) and not isinstance(look.get(k), bool)}
        if 'ev' not in clean:
            failed.append((name, 'no ev'))
            continue
        table[name] = clean
        versions.add(str(l.get('version', '')))
    return table, versions, failed


def render_js(table, version):
    """The fixture file: each look under its file name and its stem, keys in the page's order."""
    def obj(look):
        return '{' + ','.join('"%s":%s' % (k, json.dumps(look[k])) for k in KEYS if k in look) + '}'
    rows = []
    for name in sorted(table):
        rows.append('  %s: %s' % (json.dumps(name), obj(table[name])))
        stem = os.path.splitext(name)[0]
        if stem != name and stem not in table:
            rows.append('  %s: %s' % (json.dumps(stem), obj(table[name])))
    return ('// Generated by `make auto-fixtures` (Tools/auto/auto_fixtures.py) from `lumina-render auto`: AutoDevelop\'s real\n'
            '// output on the RAWs behind the sample shoot and the ARW fixtures (BRIDGE-v0.02 §1). Do not edit by hand;\n'
            '// regenerate whenever AutoDevelop changes. Keyed by file name and by stem.\n'
            'window.LuminaAutoFixturesVersion = %s;\n'
            'window.LuminaAutoFixtures = {\n%s\n};\n') % (json.dumps(version), ',\n'.join(rows))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--render', help='the lumina-render binary (make render)')
    ap.add_argument('--rules', help='rules file (default: the checkout\'s rules-v1.json)')
    ap.add_argument('--sample', default=os.path.expanduser(os.environ.get('LUMINA_SAMPLE_RAWS', '~/LuminaEvidence/sample-shoot')),
                    help='folder with the RAWs behind uploads/DSC*.jpg')
    fx = os.environ.get('LUMINA_FIXTURE_ROOT')
    ap.add_argument('--fixtures', default=os.path.join(fx, 'src') if fx else os.path.expanduser('~/LuminaEvidence/fixtures/src'),
                    help='folder with the ARW fixtures (every .ARW in it)')
    ap.add_argument('--from-jsonl', help='a saved `lumina-render auto` run instead of running it')
    ap.add_argument('--out', default=DEFAULT_OUT)
    ap.add_argument('--allow-missing', action='store_true', help='write what was found even if RAWs are missing or failed')
    a = ap.parse_args(argv)

    missing = []
    if a.from_jsonl:
        with open(a.from_jsonl, encoding='utf-8') as f:
            lines = [json.loads(l) for l in f if l.strip()]
    else:
        if not a.render:
            ap.error('--render (or --from-jsonl) is required')
        sample, missing = find_raws(a.sample, sample_stems())
        fixtures, _ = find_raws(a.fixtures)
        print('auto-fixtures: %d sample RAWs (%d missing) from %s, %d ARW fixtures from %s' % (len(sample), len(missing), a.sample, len(fixtures), a.fixtures))
        paths = list(dict.fromkeys(sample + fixtures))
        if not paths:
            raise SystemExit('auto-fixtures: no RAWs found; nothing written')
        lines = run_render(a.render, paths, a.rules)

    table, versions, failed = entries(lines)
    for s in missing:
        print('MISSING  %s.ARW (sample shoot)' % s)
    for n, why in failed:
        print('FAILED   %s: %s' % (n, why))
    if len(versions) > 1:
        raise SystemExit('auto-fixtures: more than one AutoDevelop version in one run: %s' % sorted(versions))
    if not table:
        raise SystemExit('auto-fixtures: no Auto recorded; nothing written')
    if (missing or failed) and not a.allow_missing:
        raise SystemExit('auto-fixtures: %d missing, %d failed; nothing written (--allow-missing writes the rest)' % (len(missing), len(failed)))
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    tmp = a.out + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as f:
        f.write(render_js(table, versions.pop()))
    os.replace(tmp, a.out)
    print('auto-fixtures: %d files → %s' % (len(table), a.out))
    return 0


if __name__ == '__main__':
    sys.exit(main())
